### PR TITLE
feat(git): add issue template

### PR DESCRIPTION
**Pull request by withlin**
as title

### CODE REVIEW

**Comment by mytting** [comment]
@withlin  bug-report.md  needs a simple modification


---
name: Bug Report
about: Template for bug reports
labels: kind/bug
---

# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info


- deepflow version:

  **Output of `kubectl exec -it -n deepflow sts/deepflow-server -c deepflow-server -- deepflow-server -v`:**
  **Output of `kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v`:**

  ```
  (paste your output here)
  ```

- deepflow agent list:

  **Output of `deepflow-ctl agent list`:**

  ```
  (paste your output here)
  ```

- Kubernetes CNI:

  (paste your Kubernetes CNI)

- operation-system/kernel version:

  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by withlin** [comment]
already fixed.  cc @mytting

**Comment by mytting** [comment]
> already fixed. cc @mytting
@withlin 
CNI seems not added, we do not need K8S version, but we need CNI information, because each CNI network card is different, we need to know CNI and its network card name for regular

**Comment by withlin** [comment]
done

**Review by sharang — APPROVED** [review]

**Pull request merged**
